server:
  port: 8080

spring:
  application:
    name: book

  jmx:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/ms_book
    username: root
    password: book

  thymeleaf:
    cache: false
    suffix: .html
    prefix: [classpath:/templates/publisher,
             classpath:/templates/author,
             classpath:/templates/book,]
    check-template: true

